### ISSUE TITLE
Incorrect results for Volume.contains if coordinates are negative

### ISSUE THREAD

**Issue by schlegelp** [clbarnes/ncollpyde#8] opened 2020-07-01 09:02 UTC
* ncollpyde version: 0.10.0
* Python version: 3.7.5
* Operating System: OSX

### Description
Hi! I've (somewhat randomly) tried using ncollpyde with negative coordinates and it gives unexpected results (see example). 

### What I Did

```Python
# Construct simple cube
verts = np.array([[2., 2., 2.],
       [2., 2., 0.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 2., 2.],
       [0., 2., 0.],
       [0., 0., 2.],
       [0., 0., 0.]])
faces = np.array([[4, 2, 0],
       [2, 7, 3],
       [6, 5, 7],
       [1, 7, 5],
       [0, 3, 1],
       [4, 1, 5],
       [4, 6, 2],
       [2, 6, 7],
       [6, 4, 5],
       [1, 3, 7],
       [0, 2, 3],
       [4, 0, 1]])
vol = ncollpyde.Volume(verts, faces, n_rays=3)  
# Test a point in the centre 
vol.contains([[1, 1, 1]])
True

# Now invert one axis
vol2 = ncollpyde.Volume(verts * [1, -1, 1], faces, n_rays=3)
vol2.contains([[1, -1, 1]])
False
```

**Comment by clbarnes** [comment] 2020-07-01 09:08
Interesting! Thanks for reporting, I'll take a look at this.

**Comment by aschampion** [comment] 2020-07-01 12:01
This is a face winding issue:

```py
vol3 = ncollpyde.Volume(verts * [1, -1, 1], np.fliplr(faces), n_rays=3)
vol3.contains([[1, -1, 1]])
True
```

Inverting the vertices position flips the cube inside out, so it no longer contains the point.

**Comment by schlegelp** [comment] 2020-07-01 12:09
Ah, I see! So normals are not calculated on initialisation (if this is even related to normals)?

**Comment by clbarnes** [comment] 2020-07-01 12:11
Thanks @aschampion !

You can also avoid this kind of issue (if you have trimesh installed) by using `validate=True` in the constructor - it will check for consistent and correct winding of the triangles, and for holes. It will automatically fix them in simple cases. I've got another issue open to try to do this without the extra dependency but it's not a high priority.

**Comment by schlegelp** [comment] 2020-07-01 12:12
I also just remembered the `validate` parameter which should correct winding issues according to the docs. Yet still:
```Python
vol2 = ncollpyde.Volume(verts * [1, -1, 1], faces, n_rays=3, validate=True)
vol2.contains([[1, -1, 1]]) 
False
```

**Comment by clbarnes** [comment] 2020-07-01 12:15
> Ah, I see! So normals are not calculated on initialisation (if this is even related to normals)?

Indeed, ncollide assumes that the mesh is valid and that the normals it calculates based on the winding is what you want.

**Comment by clbarnes** [comment] 2020-07-01 12:16
Overlapping comments here! Do you have trimesh installed? Without it only very basic validation will be done.

**Comment by schlegelp** [comment] 2020-07-01 12:20
Yes, trimesh (0.3.7) is installed. Does the above example with `validate=True` work in your hands?

**Comment by aschampion** [comment] 2020-07-01 12:34
It looks like trimesh is satisfied that all the faces are of a consistent winding, not what that winding is, when one doesn't pass in normals.

**Comment by clbarnes** [comment] 2020-07-01 12:40
It checks for the volume, which I thought showed as 0 if the mesh was inside out, in which case it would invert itself. I'll have a play.

**Comment by aschampion** [comment] 2020-07-01 12:45
https://github.com/mikedh/trimesh/blob/master/trimesh/base.py#L2372-L2384

**Comment by clbarnes** [comment] 2020-07-01 12:50
Yeah, I guess I was looking at https://github.com/mikedh/trimesh/blob/master/trimesh/base.py#L1543 and https://github.com/mikedh/trimesh/blob/master/trimesh/base.py#L1761 , which led me to believe that that sort of thing would be fixed.

**Comment by aschampion** [comment] 2020-07-01 12:52
It's only supposed to do automatic inversion (that's breaking our validation) if the mesh was constructed with `validate` (theirs, not ours), but that was removed in this commit: https://github.com/mikedh/trimesh/commit/f0394c671a3703e08430ef7cf0c2def2652667a3

**Comment by aschampion** [comment] 2020-07-01 12:53
I.e., this is a bug in trimesh and `is_volume` is broken for these inverted meshes because of it.

**Comment by clbarnes** [comment] 2020-07-01 14:12
I'll raise an issue on trimesh, may get to it myself at some point.

**Comment by clbarnes** [comment] 2020-07-01 15:59
PR instead of an issue but whatever https://github.com/mikedh/trimesh/pull/894

**Comment by aschampion** [comment] 2020-07-01 16:24
Won't this not fix our issue, though, because `is_volume` will still return true for us for the inverted cube because `mass_properties` will still make the volume positive because of the removed check for `validate`?

**Comment by clbarnes** [comment] 2020-07-01 16:26
It won't fix the issue directly, but it'll allow us to not bother with our own `is_volume` check and just construct the `trimesh.Trimesh` with `validate=True`, letting trimesh deal with all of the validation on construction. I think?

**Comment by aschampion** [comment] 2020-07-01 16:29
Fair enough, but the bug in trimesh persists (inverted watertight meshes have `is_volume` return true even when they are constructed with `validate=False`). Sorry, got distracted onto something else before filing any issues or anything.

**Comment by clbarnes** [comment] 2020-07-01 16:31
Yes, although I wondered whether that was expected behaviour at this point. I'll add a note to the PR.

**Comment by clbarnes** [comment] 2020-07-08 10:49
Test for this is passing in a release (0.10.1) being deployed right now.

**Comment by clbarnes** [comment] 2020-07-08 10:57
And right after that I'll release 0.10.2, where I put in the metadata to correctly expose the `validate` extra :grimacing:

**Closed** 2020-07-09 12:05 UTC
